import React,{useRef,useState} from 'react';
import {Shared,postJSON} from './Shared.jsx';
import {siteText} from './site-config.js';
export function Page(){
 const [form,setForm]=useState({name:'',email:'',organisation:'',message:'',website:''}),[errors,setErrors]=useState({}),[busy,setBusy]=useState(false),[alert,setAlert]=useState('');const refs=useRef({}),alertRef=useRef();
 const validate=value=>({name:!value.name.trim(),email:!/^\S+@[^\s@]+\.[^\s@]{2,}$/.test(value.email.trim()),message:value.message.trim().length<10});
 const update=(key,value)=>{const next={...form,[key]:value};setForm(next);if(Object.values(errors).some(Boolean))setErrors(validate(next));};
 async function submit(event){event.preventDefault();if(busy)return;setAlert('');const next=validate(form);setErrors(next);const first=Object.keys(next).find(key=>next[key]);if(first){refs.current[first]?.focus();return;}setBusy(true);try{await postJSON('/api/contact',Object.fromEntries(Object.entries(form).map(([k,v])=>[k,k==='website'?v:v.trim()])));location.href='/thank-you';}catch(e){setAlert(e.message);setBusy(false);requestAnimationFrame(()=>alertRef.current?.scrollIntoView({block:'nearest'}));}}
 const props=key=>({name:key,value:form[key],onChange:e=>update(key,e.target.value),ref:el=>{refs.current[key]=el;},'aria-invalid':errors[key]||undefined,'aria-describedby':errors[key]?'e-'+key:undefined});
 return <Shared><a className="skip-link" href="#main">Skip to content</a><header className="pub-header"><div className="in"><a href="/login" aria-label="empower-fin Dashboard Portal home"><img src="/static/logo.png" alt="empower-fin logo"/></a><nav aria-label="Primary"><a href="/privacy">Privacy</a><a href="/terms">Terms</a><a href="/contact">Contact</a><a className="keep" href="/login">Sign in</a></nav></div></header>
 <main id="main" className="pub-main"><div className="panel"><p className="eyebrow">Contact</p><h1>Request access or ask a question</h1><p className="lead">Tell us about your organisation and what you need. We reply within two business days. You can also write to <a href={siteText('mailto:{{CONTACT_EMAIL}}')}><strong>{siteText('{{CONTACT_EMAIL}}')}</strong></a>.</p><div ref={alertRef} id="form-alert" className={'form-alert'+(alert?' show':'')} role="alert">{alert}</div>
 <form id="contact-form" noValidate onSubmit={submit}>
 <div className={'field'+(errors.name?' has-error':'')}><label htmlFor="c-name">Full name</label><input id="c-name" autoComplete="name" required maxLength={120} {...props('name')}/><div className="field-error" id="e-name">Please enter your name.</div></div>
 <div className={'field'+(errors.email?' has-error':'')}><label htmlFor="c-email">Work email</label><input id="c-email" type="email" autoComplete="email" required maxLength={254} {...props('email')}/><div className="field-error" id="e-email">Please enter a valid email address.</div></div>
 <div className="field"><label htmlFor="c-org">Organisation <span style={{textTransform:'none',letterSpacing:0,fontWeight:500}}>(optional)</span></label><input id="c-org" autoComplete="organization" maxLength={120} {...props('organisation')}/></div>
 <div className={'field'+(errors.message?' has-error':'')}><label htmlFor="c-msg">How can we help?</label><textarea id="c-msg" required minLength={10} maxLength={2000} {...props('message')}/><div className="hint"><span id="c-count">{form.message.length}</span> / 2000</div><div className="field-error" id="e-message">Please write at least 10 characters.</div></div>
 <div className="hp" aria-hidden="true"><label>Leave blank<input id="c-web" tabIndex={-1} autoComplete="off" {...props('website')}/></label></div><button className="ent-cta primary" id="c-btn" type="submit" style={{width:'100%'}} disabled={busy} aria-busy={busy||undefined}>{busy?<><span className="spin"/>Sending…</>:'Send message'}</button></form></div></main>
 <footer className="pub-footer"><span>© empower-fin · {siteText('{{CONTACT_ADDRESS}}')}</span><span><a href="/privacy">Privacy Policy</a> · <a href="/terms">Terms</a> · <a href="/cookies">Cookies</a> · <a href={siteText('mailto:{{CONTACT_EMAIL}}')}>{siteText('{{CONTACT_EMAIL}}')}</a></span></footer><div className="sticky-cta"><a className="ent-cta" href="/contact">Request access</a></div></Shared>;
}
