import React,{useEffect,useLayoutEffect,useRef,useState} from 'react';
import {Shared,useCookieNotice,postJSON} from './Shared.jsx';
import {siteText} from './site-config.js';
export function Page(){
 const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[remember,setRemember]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false),[invalid,setInvalid]=useState('');
 const [forgot,setForgot]=useState(false),[forgotEmail,setForgotEmail]=useState(''),[forgotMessage,setForgotMessage]=useState(''),[sending,setSending]=useState(false),[forgotError,setForgotError]=useState(false);
 const [theme,setTheme]=useState(null),[cookie,dismiss]=useCookieNotice();const emailRef=useRef(),passwordRef=useRef();
 const [dark,setDark]=useState(()=>{try{const saved=localStorage.getItem('ef_theme');return saved?saved==='dark':matchMedia('(prefers-color-scheme: dark)').matches;}catch{return false;}});
 useLayoutEffect(()=>{document.documentElement.dataset.theme=dark?'dark':'light';},[dark]);
 useEffect(()=>{
  const slug=new URLSearchParams(location.search).get('partner');if(!slug)return;
  const abort=new AbortController();fetch('/api/partner-theme/'+encodeURIComponent(slug),{signal:abort.signal}).then(r=>r.ok?r.json():null).then(value=>{if(value)setTheme(value);}).catch(()=>{});return()=>abort.abort();
 },[]);
 useEffect(()=>{if(!theme)return;const style=document.documentElement.style;for(const [field,token]of [['accentColor','--blue'],['navyColor','--brand-primary'],['primaryColor','--ice']])if(theme[field])style.setProperty(token,'#'+String(theme[field]).replace(/^#/,''));if(theme.name)document.title=theme.name+' — Sign in';},[theme]);
 async function signIn(){
  if(busy)return;setError('');setInvalid('');
  if(!email.trim()||!password){const field=!email.trim()?'email':'password';setInvalid(field);setError(field==='email'?'Enter your email address.':'Enter your password.');(field==='email'?emailRef:passwordRef).current.focus();return;}
  setBusy(true);try{await postJSON('/api/auth/login',{email,password,remember});const response=await fetch('/api/auth/me');if(!response.ok)throw new Error('Could not load your access permissions. Please sign in again.');const me=await response.json();location.href=me.modules?.dashboard?'/dashboard':me.modules?.admin?'/admin':'/dashboard';}catch(e){setError(e.message);setInvalid('password');setBusy(false);}
 }
 async function sendForgot(){if(sending)return;if(!forgotEmail.trim()){setForgotError(true);setForgotMessage('Enter your email first.');return;}setSending(true);setForgotError(false);try{await postJSON('/api/auth/forgot-password',{email:forgotEmail.trim()});}catch{}setForgotMessage('If an account exists for that email, a reset link is on its way. Check your inbox (and spam folder).');setSending(false);}
 const toggle=()=>setDark(value=>{try{localStorage.setItem('ef_theme',value?'light':'dark');}catch{}return !value;});
 return <Shared ownCookie>
 <aside className="auth-side"><div><img src="/static/logo-large.png" alt="empower-fin logo" id="side-logo"/></div><div><h2>Financial wellbeing, measured with rigour.</h2><p>A secure analytics workspace giving employers and their partners a clear, auditable view of workforce financial health.</p><ul><li>Role-based access with full administrative audit trail</li><li>Encrypted sessions and an enforced password policy</li><li>Every score calculated from your own source data</li></ul></div><a className="ent-cta ghost side-cta" href="/contact" style={{alignSelf:'flex-start'}}>Request access</a><small>© empower-fin &nbsp;·&nbsp; Confidential &nbsp;·&nbsp; <a href={siteText('mailto:{{CONTACT_EMAIL}}')} style={{color:'inherit'}}>{siteText('{{CONTACT_EMAIL}}')}</a></small></aside>
 <main className="auth-main"><div className="card" style={{display:forgot?'none':undefined}}>
 <div className="logo"><img src={theme?.logoDataUrl||'/static/logo-large.png'} data-custom-logo={theme?.logoDataUrl?'1':undefined} alt="empower-fin Dashboard Portal" style={{height:54,width:'auto'}}/></div><h1>Sign in to your workspace</h1><div className="sub" id="brand-sub">{theme?.tagline||theme?.name||'Employee financial wellbeing platform'}</div>
 <label htmlFor="email">Email</label><input ref={emailRef} id="email" type="email" autoComplete="username" placeholder="you@company.com" required aria-describedby="err" aria-invalid={invalid==='email'||undefined} value={email} onChange={e=>setEmail(e.target.value)}/>
 <label htmlFor="password">Password</label><input ref={passwordRef} id="password" type="password" autoComplete="current-password" placeholder="••••••••" aria-invalid={invalid==='password'||undefined} value={password} onChange={e=>setPassword(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')signIn();}}/>
 <div style={{textAlign:'right',marginTop:8}}><a href="#" id="forgot-link" onClick={e=>{e.preventDefault();setForgot(true);setForgotEmail(email);setForgotMessage('');}} style={{fontSize:12.5,fontWeight:700,color:'var(--blue-d)',textDecoration:'none'}}>Forgot password?</a></div>
 <label style={{display:'flex',alignItems:'center',gap:8,margin:'16px 0 0',fontWeight:600,fontSize:13,color:'var(--grey)',cursor:'pointer'}}><input id="remember" type="checkbox" checked={remember} onChange={e=>setRemember(e.target.checked)} style={{width:'auto',margin:0,accentColor:'var(--brand-primary)',cursor:'pointer'}}/>Remember me</label>
 <button id="btn" onClick={signIn} disabled={busy} aria-busy={busy||undefined}>{busy?'Signing in…':'Sign in'}</button><div className="err" id="err" role="alert" style={{display:error?'block':'none'}}>{error}</div><div className="err" id="deactivated-msg" style={{display:new URLSearchParams(location.search).get('deactivated')==='1'?'block':'none',background:'#eef2ff',color:'#32217c'}}>Your account has been deactivated. Contact an administrator if you'd like access restored.</div></div>
 <div className="card" id="forgot-card" style={{display:forgot?'block':'none'}}><h1 style={{marginTop:0}}>Reset your password</h1><div className="sub">Enter your email and we'll send you a reset link, if an account exists.</div><label htmlFor="forgot-email">Email</label><input id="forgot-email" type="email" autoComplete="username" placeholder="you@company.com" value={forgotEmail} onChange={e=>setForgotEmail(e.target.value)}/><button id="forgot-btn" disabled={sending} onClick={sendForgot}>{sending?'Sending…':'Send reset link'}</button><div style={{textAlign:'center',marginTop:16}}><a href="#" onClick={e=>{e.preventDefault();setForgot(false);}} style={{fontSize:12.5,fontWeight:700,color:'var(--grey)',textDecoration:'none'}}>← Back to sign in</a></div><div className="err" id="forgot-msg" style={{display:forgotMessage?'block':'none',background:forgotError?'#fdecea':'#e7f7ef',color:forgotError?'#b5391f':'#137a47'}}>{forgotMessage}</div></div>
 <div style={{textAlign:'center',marginTop:18,fontSize:12,color:'#8497a7'}}><a href="/privacy" style={{color:'#8497a7'}}>Privacy Policy</a> · <a href="/terms" style={{color:'#8497a7'}}>Terms of Service</a> · <a href="/cookies" style={{color:'#8497a7'}}>Cookie Notice</a></div></main>
 <div className="sticky-cta"><a className="ent-cta" href="/contact">Request access</a></div><div id="cookie-banner" style={{display:cookie?'block':'none'}}><div className="inner"><p>We use a strictly necessary cookie to keep you signed in — no advertising or tracking cookies. See our <a href="/cookies">Cookie Notice</a> for details.</p><div className="actions"><button className="dismiss" onClick={dismiss}>Dismiss</button><button className="accept" onClick={dismiss}>Got it</button></div></div></div>
 <button id="theme-toggle-btn" type="button" data-no-invert="" onClick={toggle} aria-label={dark?'Switch to light mode':'Switch to dark mode'}>{dark?'☀️':'🌙'}</button>
 </Shared>;
}
