import { useEffect, useMemo, useState } from "react";
import type { CSSProperties } from "react";
import { Badge } from "./ui/badge";
import { Button } from "./ui/button";
import { Card, CardContent, CardHeader } from "./ui/card";

type Theme = { primary?: string; accent?: string; navy?: string };
type EmployerRef = { id: string; name: string };
type DashboardLike = {
  income?: Array<{name:string;count:number;color?:string}>;
  ratings?: {avg:number|null;fiveStarPct:number|null;responses:number|null};
  filterOptions?: {sites?:Array<{value:string;label:string}>};
  stressBySite?: Array<{name:string;stress:number}>;
  riskSignals?: Array<{sig:string;n:number;sev:string;note:string}>;
  chat?: {available?:boolean;conversations?:number;resolvedInChat?:number;avgFirstReply?:string;csat?:number;journeys?:Array<{name:string;count:number;share?:number}>;trending?:Array<{question:string;count:number;change?:number}>;themes?:Array<{theme:string;count:number;sentiment?:number}>};
  kpis?: {activated?:{pct:number|null;count:number|null}};
};

const num=(v:number|null|undefined)=>v==null||!Number.isFinite(Number(v))?"Not available":Math.round(Number(v)).toLocaleString("en-ZA");
const money=(v:number|null|undefined)=>v==null||!Number.isFinite(Number(v))?"Not available":"R "+Math.round(Number(v)).toLocaleString("en-ZA");
const pct=(v:number|null|undefined)=>v==null||!Number.isFinite(Number(v))?"Not available":Math.round(Number(v))+"%";

export function NewChangesParitySections({data}:{data:DashboardLike}) {
  const stress=data.stressBySite||[];
  const rating=data.ratings;
  const chat=data.chat;
  return <>
    <section className="dash-section" data-section="stressMap">
      <div className="head" style={{padding:"36px 0 14px"}}><div><div className="head-eyebrow">Where the pressure sits</div><h1 style={{fontSize:27}}>Financial pressure across the workforce</h1><div className="head-sub">Financial pressure is not evenly spread. This view identifies where it concentrates so the programme can be directed to the people and sites that need it most.</div></div></div>
      <div className="stat-strip">
        <div className="stat-cell"><div className="l">Sites represented</div><div className="v">{num(data.filterOptions?.sites?.length)}</div><div className="d">authorised sites</div></div>
        <div className="stat-cell"><div className="l">Highest site stress</div><div className="v">{stress.length?Math.max(...stress.map(x=>x.stress)):"Not available"}</div><div className="d">{stress.length?"index / 100":"site stress feed unavailable"}</div></div>
        <div className="stat-cell"><div className="l">Employees activated</div><div className="v">{num(data.kpis?.activated?.count)}</div><div className="d">{pct(data.kpis?.activated?.pct)} of workforce</div></div>
      </div>
      <div className="grid g-12 section-gap">
        <Card style={{gridColumn:"span 4"}}><CardHeader><div className="card-title">Stress index by site</div><div className="card-note">Higher = more financial pressure.</div></CardHeader><CardContent>{stress.length?<div className="hbar">{stress.map(row=><div className="hbar-row" key={row.name}><div className="hbar-lbl">{row.name}</div><div className="hbar-track"><div className="hbar-fill" style={{width:String(Math.max(0,Math.min(100,row.stress)))+"%",background:"var(--brand-accent)"}}/></div><div className="hbar-val">{row.stress}</div></div>)}</div>:<div className="muted" style={{padding:"28px 8px"}}>Site stress data is not available for this reporting view. No missing value is treated as zero.</div>}</CardContent></Card>
        <Card style={{gridColumn:"span 4"}}><CardHeader><div className="card-title">Who the programme is reaching</div><div className="card-note">Activated employees by income band.</div></CardHeader><CardContent>{data.income?.length?<div className="legend">{data.income.map(row=><div className="legend-row" key={row.name}><span className="legend-dot" style={{background:row.color||"var(--brand-accent)"}}/><span className="legend-name">{row.name}</span><span className="legend-val">{num(row.count)}</span></div>)}<div className="legend-sub">Income-band reach among activated employees in the selected view.</div></div>:<div className="muted" style={{padding:"28px 8px"}}>Income-band data is not available for this period.</div>}</CardContent></Card>
        <Card style={{gridColumn:"span 4"}}><CardHeader><div className="card-title">How employees rate us</div><div className="card-note">From end-of-journey ratings.</div></CardHeader><CardContent>{rating?.avg!=null?<><div className="rating-hero"><div className="rating-big">{rating.avg.toFixed(1)}</div><div><div className="rating-stars" aria-label={rating.avg.toFixed(1)+" out of 5"}>★★★★★</div><div className="text-[10px] text-slate-500">{num(rating.responses)} ratings</div></div></div><div className="rating-share-pill"><div><div className="l">5-star ratings</div></div><div className="v">{pct(rating.fiveStarPct)}</div></div></>:<div className="muted" style={{padding:"28px 8px"}}>Employee rating data is not available for this reporting view.</div>}</CardContent></Card>
      </div>
    </section>
    <section className="dash-section" data-section="voiceOfEmployee">
      <div className="head" style={{padding:"36px 0 14px"}}><div><div className="head-eyebrow">Voice of the employee</div><h1 style={{fontSize:27}}>What employees are asking</h1><div className="head-sub">Questions from the separate chat integration, categorised by journey.</div></div></div>
      {!chat||chat.available===false?<div className="card section-gap"><div className="muted" style={{padding:"34px 18px",textAlign:"center"}}>Chat data is supplied by the separate chat integration and is not currently available.</div></div>:<><div className="grid g-4">{[["Total conversations",num(chat.conversations)],["Resolved in chat",pct(chat.resolvedInChat)],["Avg first reply",chat.avgFirstReply||"Not available"],["Chat satisfaction",chat.csat==null?"Not available":chat.csat.toFixed(1)+"/5"]].map(([l,v])=><Card className="portal-kpi" key={l}><CardContent className="p-5"><span className="portal-kpi-label">{l}</span><strong className="portal-number portal-kpi-value mt-3 block">{v}</strong></CardContent></Card>)}</div><div className="grid g-12 section-gap"><Card style={{gridColumn:"span 7"}}><CardHeader><div className="card-title">Conversations by journey</div><div className="card-note">Where questions are coming from.</div></CardHeader><CardContent>{(chat.journeys||[]).map(x=><div className="funnel-row" key={x.name}><div className="funnel-lbl">{x.name}<small>{x.share==null?"":pct(x.share)}</small></div><div className="funnel-bar-bg"><div className="funnel-bar" style={{width:String(Math.min(100,x.share||0))+"%",background:"var(--brand-accent)"}}/></div><div className="funnel-val">{num(x.count)}</div></div>)}</CardContent></Card><Card style={{gridColumn:"span 5"}}><CardHeader><div className="card-title">Trending questions</div><div className="card-note">Rising across the workforce this period.</div></CardHeader><CardContent>{(chat.trending||[]).map(x=><div className="outcome" key={x.question}><div><div className="outcome-name">{x.question}</div><div className="outcome-meta">{num(x.count)} conversations</div></div><Badge>{x.change==null?"":(x.change>0?"+":"")+x.change+"%"}</Badge></div>)}</CardContent></Card></div><Card className="section-gap"><CardHeader><div className="card-title">Chat themes</div><div className="card-note">Themes from the separate chat data source.</div></CardHeader><CardContent>{(chat.themes||[]).map(x=><div className="stat-cell" key={x.theme}><div className="l">{x.theme}</div><div className="v">{num(x.count)}</div><div className="d">{x.sentiment==null?"":pct(x.sentiment)+" positive"}</div></div>)}</CardContent></Card></>}
    </section>
  </>;
}

type PortfolioRow = EmployerRef & {heads?:number;takeUp?:number|null;engaged?:number|null;wellness?:number|null;saving?:number|null;betterOff?:number|null;rating?:number|null;fiveStarPct?:number|null;oppValue?:number|null};

export function PortfolioView({employers,theme,onBack}:{employers:EmployerRef[];theme?:Theme;onBack:()=>void}) {
  const [rows,setRows]=useState<PortfolioRow[]>([]);
  const [loading,setLoading]=useState(true);
  const [metric,setMetric]=useState<keyof PortfolioRow>("oppValue");
  const [selected,setSelected]=useState<Set<string>>(()=>new Set(employers.map(e=>e.id)));
  const [search,setSearch]=useState(""); const [filterOpen,setFilterOpen]=useState(false); const [windowLabel,setWindowLabel]=useState("Programme to date");
  const primary=theme?.primary||"#214b45", accent=theme?.accent||"#8a6f3d";
  useEffect(()=>{let alive=true;(async()=>{setLoading(true);try{const q=new URLSearchParams(window.location.search);if(!q.has("period")&&!q.has("quarter")&&!q.has("range"))q.set("range","latest");const res=await fetch("/api/portfolio?"+q.toString(),{credentials:"include",cache:"no-store"});if(!res.ok)throw new Error("portfolio unavailable");const d=await res.json();const allowed=new Set(employers.map(e=>e.id));const incoming=Array.isArray(d.employers)?d.employers:[];const normalised= incoming.filter((e:any)=>!e.id||allowed.has(e.id)).map((e:any)=>({id:String(e.id),name:String(e.name||e.employer||e.id),heads:e.heads??e.headcount,takeUp:e.takeUp??e.kpis?.takeUp?.pct,engaged:e.engaged??e.kpis?.activated?.pct,wellness:e.wellness?.score??e.wellness,saving:e.saving??e.kpis?.monthlySaving?.rand,betterOff:e.betterOff,rating:e.rating??e.ratings?.avg,fiveStarPct:e.fiveStarPct??e.ratings?.fiveStarPct,oppValue:e.oppValue??e.opportunityValue??null,...e}));if(alive){setRows(normalised);setSelected(new Set(normalised.map((e:any)=>e.id)));setWindowLabel(d.filterContext?.label||"Programme to date");}}catch{if(alive){const fallback=employers.map(e=>({id:e.id,name:e.name}));setRows(fallback);setSelected(new Set(fallback.map(e=>e.id)));setWindowLabel("Live portfolio feed unavailable");}}finally{if(alive)setLoading(false);}})();return()=>{alive=false}},[employers]);
  const visible=useMemo(()=>rows.filter(r=>selected.has(r.id)).slice().sort((a,b)=>Number(b[metric]??-Infinity)-Number(a[metric]??-Infinity)),[rows,selected,metric]);
  const filteredOptions=useMemo(()=>rows.filter(r=>r.name.toLowerCase().includes(search.trim().toLowerCase())),[rows,search]);
  const metrics:[keyof PortfolioRow,string,string][]=[["takeUp","Take-up","%"],["engaged","Active engagement","%"],["wellness","Financial Wellness Score",""],["saving","Cashflow / mo","R"],["betterOff","Better off","n"],["oppValue","Opportunity / mo","R"],["rating","Rating","/5"],["fiveStarPct","5-star share","%"]];
  const fmt=(u:string,v:any)=>v==null?"Not available":u==="R"?money(v):u==="%"?pct(v):u==="/5"?Number(v).toFixed(1):num(v);
  const style={"--brand-primary":primary,"--brand-accent":accent} as CSSProperties; const allSelected=rows.length>0&&selected.size===rows.length;
  const toggle=(id:string)=>setSelected(prev=>{const n=new Set(prev);if(n.has(id))n.delete(id);else n.add(id);return n});
  return <main className="dashboard-shell" style={style}><div className="topbar"><div className="topbar-inner"><div className="logo"><span className="logo-mark">EF</span><span className="logo-text">Portfolio insights</span></div><div className="topbar-spacer"/><Button variant="outline" onClick={onBack}>Employer view</Button></div></div><div className="wrap">
    <div className="pf-banner">Internal portfolio view — authorised empower-fin and channel partner users only. Not shared with employers.</div>
    <div className="head" style={{padding:"26px 0 18px"}}><div><div className="head-eyebrow">Across all employer clients</div><h1 style={{fontSize:34}}>Portfolio insights</h1><div className="head-sub">Every reportable metric, across your whole book of employers. Spot where opportunity is highest, where satisfaction is slipping, and where financial stress is concentrated — at a glance.</div></div><div className="head-actions"><Button variant="outline" onClick={()=>window.print()}>Export book</Button></div></div>
    <div className="pf-toolbar" style={{display:"flex",justifyContent:"space-between",gap:16,flexWrap:"wrap",marginBottom:20}}><div style={{position:"relative",minWidth:300}}><div className="pf-filter-label">Employers</div><Button variant="outline" onClick={()=>setFilterOpen(v=>!v)} aria-expanded={filterOpen}>{allSelected?"All employers ("+rows.length+")":selected.size+" of "+rows.length+" employers"}⌄</Button>{filterOpen&&<div className="card" style={{position:"absolute",zIndex:20,top:"100%",left:0,width:320,padding:12}}><div className="flex gap-2 mb-2"><Button variant="outline" onClick={()=>setSelected(new Set(rows.map(r=>r.id)))}>Select all</Button><Button variant="outline" onClick={()=>setSelected(new Set())}>Clear all</Button></div><input className="w-full rounded-md border px-3 py-2 text-sm" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search employers…" /><div className="mt-2 max-h-56 overflow-auto">{filteredOptions.map(r=><label className="flex items-center gap-2 py-2 text-sm" key={r.id}><input type="checkbox" checked={selected.has(r.id)} onChange={()=>toggle(r.id)}/><span>{r.name}</span></label>)}</div></div>}<div className="pf-scope-note" style={{marginTop:6}}>{selected.size?selected.size+" employer"+(selected.size===1?"":"s")+" selected · "+rows.filter(r=>selected.has(r.id)).reduce((n,r)=>n+(Number(r.heads)||0),0).toLocaleString("en-ZA")+" employees covered":"No employers selected."}</div></div><div className="pf-toolbar-right"><span className="pf-window-pill">Reporting window: {windowLabel}</span><span className="pf-window-pill">Missing measures remain unavailable</span></div></div>
    {loading?<Card><CardContent className="py-12 text-center text-sm text-slate-500">Loading portfolio data...</CardContent></Card>:selected.size===0?<Card><CardContent className="py-12 text-center text-sm text-slate-500">No employers selected. Choose at least one employer above.</CardContent></Card>:<><div className="grid g-4">{[["Employers",visible.length],["Headcount",visible.reduce((n,r)=>n+(Number(r.heads)||0),0)],["Monthly cashflow",visible.reduce((n,r)=>n+(Number(r.saving)||0),0)],["Average rating",visible.filter(r=>r.rating!=null).length?(visible.reduce((n,r)=>n+Number(r.rating||0),0)/visible.filter(r=>r.rating!=null).length).toFixed(1):"Not available"]].map(([l,v])=><Card className="portal-kpi" key={String(l)}><CardContent className="p-5"><span className="portal-kpi-label">{l}</span><strong className="portal-number portal-kpi-value mt-3 block">{typeof v==="number"&&String(l)!=="Average rating"?num(v):v}</strong></CardContent></Card>)}</div>
      <Card className="section-gap"><CardHeader><div className="card-title">Portfolio heatmap</div><div className="card-note">Every employer, every metric. Click a column to rank the league table.</div></CardHeader><CardContent><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-xs"><thead><tr><th className="border-b p-3 text-[10px] uppercase tracking-wide text-slate-500">Employer</th>{metrics.map(([k,l,u])=><th className="border-b p-3 text-[10px] uppercase tracking-wide text-slate-500" key={String(k)}><button type="button" onClick={()=>setMetric(k)}>{l} {u}</button></th>)}</tr></thead><tbody className="divide-y divide-slate-100">{visible.map(row=><tr key={row.id}><td className="p-3 font-semibold">{row.name}<div className="text-[10px] text-slate-500">{num(row.heads)} staff</div></td>{metrics.map(([k,,u])=><td className="p-3" key={String(k)}>{fmt(u,row[k])}</td>)}</tr>)}</tbody></table></div></CardContent></Card>
      <Card className="section-gap"><CardHeader><div className="card-title">League table</div><div className="card-note">Employers ranked by selected metric.</div></CardHeader><CardContent><div className="flex flex-wrap gap-2 mb-3">{metrics.map(([k,l])=><Button key={String(k)} variant={metric===k?"default":"outline"} onClick={()=>setMetric(k)}>{l}</Button>)}</div><div className="space-y-1">{visible.map((row,i)=><div className="grid grid-cols-[42px_1fr_auto] items-center gap-3 border-b border-slate-100 py-3" key={row.id}><strong style={{color:accent}}>{String(i+1).padStart(2,"0")}</strong><span className="font-semibold">{row.name}</span><strong style={{color:primary}}>{fmt(metrics.find(m=>m[0]===metric)?.[2]||"",row[metric])}</strong></div>)}</div></CardContent></Card></>}</div></main>;